project_name: local-pvc-cleaner
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1

kos:
  - repositories:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | tolower }}/{{.ProjectName}}
    tags:
      - "{{.Tag}}"
      - latest
    bare: true
    base_image: alpine
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

release:
  draft: false
  disable: false
  skip_upload: true
