project_name: local-pvc-cleaner
version: 2

builds:
  - goos:
      - linux
    goarch:
      - amd64

dockers:
  - image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | tolower }}/{{.ProjectName}}:{{ .Tag }}
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | tolower }}/{{.ProjectName}}:latest
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

release:
  draft: false
  disable: false
  skip_upload: true